export const CINEMATIC_PRESETS = {
  WARM: {
    id: 'warm',
    name: 'Warm',
    description: 'Warm, inviting tones',
    category: 'warm',
    settings: {
      temperature: 15,
      tint: 0,
      exposure: 0,
      contrast: 5,
      highlights: -10,
      shadows: 10,
      whites: 5,
      blacks: -5,
      saturation: 10,
      vibrance: 15,
      grain: 0,
      vignette: 10,
    },
  },
  COOL: {
    id: 'cool',
    name: 'Cool',
    description: 'Cool, calming tones',
    category: 'cool',
    settings: {
      temperature: -15,
      tint: 0,
      exposure: 0,
      contrast: 5,
      highlights: -5,
      shadows: 5,
      whites: -5,
      blacks: 5,
      saturation: 5,
      vibrance: 10,
      grain: 0,
      vignette: 15,
    },
  },
  BW: {
    id: 'bw',
    name: 'Black & White',
    description: 'Classic monochrome',
    category: 'bw',
    settings: {
      temperature: 0,
      tint: 0,
      exposure: 0,
      contrast: 20,
      highlights: -20,
      shadows: 15,
      whites: 10,
      blacks: -15,
      saturation: -100,
      vibrance: 0,
      grain: 10,
      vignette: 20,
    },
  },
  VINTAGE: {
    id: 'vintage',
    name: 'Vintage Film',
    description: 'Retro film look',
    category: 'vintage',
    settings: {
      temperature: 10,
      tint: 5,
      exposure: 5,
      contrast: -10,
      highlights: -15,
      shadows: 20,
      whites: 5,
      blacks: 10,
      saturation: -20,
      vibrance: -10,
      grain: 25,
      vignette: 30,
    },
  },
  MODERN: {
    id: 'modern',
    name: 'Modern Digital',
    description: 'Clean, digital look',
    category: 'modern',
    settings: {
      temperature: 0,
      tint: 0,
      exposure: 5,
      contrast: 15,
      highlights: -10,
      shadows: 5,
      whites: 10,
      blacks: -10,
      saturation: 15,
      vibrance: 20,
      grain: 0,
      vignette: 5,
    },
  },
  TEAL_ORANGE: {
    id: 'teal-orange',
    name: 'Teal & Orange',
    description: 'Popular cinematic look',
    category: 'modern',
    settings: {
      temperature: 5,
      tint: -5,
      exposure: 0,
      contrast: 10,
      highlights: -15,
      shadows: 10,
      whites: 5,
      blacks: -5,
      saturation: 20,
      vibrance: 25,
      grain: 5,
      vignette: 15,
    },
  },
  MOODY: {
    id: 'moody',
    name: 'Moody Dark',
    description: 'Dark, atmospheric',
    category: 'cool',
    settings: {
      temperature: -10,
      tint: 0,
      exposure: -10,
      contrast: 20,
      highlights: -30,
      shadows: -10,
      whites: -15,
      blacks: -20,
      saturation: -15,
      vibrance: -10,
      grain: 15,
      vignette: 35,
    },
  },
  BRIGHT_AIRY: {
    id: 'bright-airy',
    name: 'Bright & Airy',
    description: 'Light, airy aesthetic',
    category: 'warm',
    settings: {
      temperature: 5,
      tint: 5,
      exposure: 15,
      contrast: -15,
      highlights: -20,
      shadows: 25,
      whites: 20,
      blacks: 15,
      saturation: -10,
      vibrance: 5,
      grain: 0,
      vignette: 5,
    },
  },
  CYBERPUNK: {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'Neon-lit future',
    category: 'other',
    settings: {
      temperature: -5,
      tint: 15,
      exposure: 5,
      contrast: 25,
      highlights: -10,
      shadows: 5,
      whites: 10,
      blacks: -15,
      saturation: 30,
      vibrance: 40,
      grain: 10,
      vignette: 20,
    },
  },
  FILM_NOIR: {
    id: 'film-noir',
    name: 'Film Noir',
    description: 'Classic noir style',
    category: 'bw',
    settings: {
      temperature: 0,
      tint: 0,
      exposure: -5,
      contrast: 30,
      highlights: -25,
      shadows: -15,
      whites: 15,
      blacks: -25,
      saturation: -100,
      vibrance: 0,
      grain: 30,
      vignette: 40,
    },
  },
} as const

export const PRESET_CATEGORIES = [
  { id: 'warm', name: 'Warm', icon: '☀️' },
  { id: 'cool', name: 'Cool', icon: '❄️' },
  { id: 'bw', name: 'Black & White', icon: '⚫' },
  { id: 'vintage', name: 'Vintage', icon: '📼' },
  { id: 'modern', name: 'Modern', icon: '✨' },
  { id: 'other', name: 'Other', icon: '🎨' },
] as const

export type PresetId = keyof typeof CINEMATIC_PRESETS
export type PresetCategory = (typeof PRESET_CATEGORIES)[number]['id']
